### ISSUE TITLE
question and bug report

### ISSUE THREAD

**Issue by lila** [gc3-uzh-ch/elasticluster#393]
I am using elasticluster with GCE to build slurm cluster.  Below are some issues that I had that seem to be due to debian 8 support.  What OS/distro should i use that has the best support?

1. dbus package missing on debian 8 vanilla distribution.  I added 

```
image_userdata=#!/bin/bash
  apt-get update && apt-get install -y dbus
```

to the config, but it seems that the GCE plugin scripts ignore the userdata and do not use it when spinning up the instance.  so you have to manually log in and install dbus.

in gce.py:

```           
"metadata": {
                "kind": "compute#metadata",
                "items": [
                    {
                        "key": "sshKeys",
                        "value": "%s:%s" % (username, public_key_content)
                    }
                ]
            }
        }
```

should have the following added to the array of items:

```
{
        # Startup script is automatically executed by the
        # instance upon startup.
        "key": "startup-script",
         "value": image_userdata
   }
```

2. even though i'm running debian 8, there are many places where the playbook directive is_debian_8_or_later seems to be inconsistent.

for example, in `elasticluster/share/playbooks/roles/slurm-client/tasks/main.yml` or in `elasticluster/share/playbooks/roles/slurm-master/tasks/init-Debian.yml`.  looking at the latter:

```
- name: Set SLURM master playbook params (Debian/Ubuntu)
  set_fact:
    slurmctld_service_name: slurmctld
    slurmctld_packages:
      - mailutils
      - slurmctld
    slurmdbd_service_name: slurmdbd
    slurmdbd_packages:
      - slurmdbd
  when:
    '{{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}}'
```

does not set the slurmbd packages.  if i delete the when clause it's fine.  the `is_debian_8_or_later` clause seems to be inconsistently set.  sometimes its correct, sometimes its not.  

any advice here?

or in general, what would you all recommend for the best supported distribution?

cheers,

- k
