### ISSUE TITLE
Is slurm meant to work without any changes to the playbook?

### ISSUE THREAD

**Issue by kuzlovsky** [gc3-uzh-ch/elasticluster#418]
Hello,

I found elasticluster a few weeks ago and I really loved the concept and what it could do. I was trying to set it up with slurm for 3 days now but I did not have much progress. I am running out of time for my project and I either need to abadon it or ask for help...

This is what I can see from [startup log](https://hastebin.com/jajajizahi.md)

Running the setup again does not fix the issue

I was using ami-627d4a04 on AWS

The problem seems to be this on the compute node:
```
ubuntu@compute001:~$ sudo mount /home/
YPBINDPROC_DOMAIN: Domain not bound
```

I tried to troubleshoot it myself but did not get very far:
```
ubuntu@compute001:~$ cat /etc/fstab
LABEL=cloudimg-rootfs   /        ext4   defaults,discard        0 0
/dev/xvdb       /mnt    auto    defaults,nobootwait,comment=cloudconfig 0       2
frontend001:/home /home nfs rw,async 0 0
```

On the frontend:
```
ubuntu@frontend001:~$ cat /etc/exports 
#
...
#
/home compute001(rw,no_root_squash,async,no_subtree_check,crossmnt)

```

```
ubuntu@frontend001:~$ sudo showmount -e localhost
Export list for localhost:
/home compute001

```

Then after 2 days, as a workaround, I just disabled NIS:
```
- name: Slurm master Playbook
  hosts: slurm_master
  roles:
    #- role: 'nis'
    #  NIS_MASTER: "{{groups.slurm_master[0]}}"
    #- role: 'nfs-server'
    #  NFS_EXPORTS:
    #    - path: '/home'
    #      clients: "{{groups.slurm_worker + groups.slurm_submit|default([])}}"
    - slurm-master


- name: Slurm worker nodes Playbook
  hosts: slurm_worker
  roles:
    #- role: 'nis'
    #  NIS_MASTER: "{{groups.slurm_master[0]}}"
    #- role: 'nfs-client'
    #  NFS_MOUNTS:
    #    - fs: '{{groups.slurm_master[0]}}:/home'
    #      mountpoint: '/home'
    - slurm-worker


- name: Slurm submit nodes Playbook
  hosts: slurm_submit:slurm_client
  roles:
    #- role: 'nis'
    #  NIS_MASTER: "{{groups.slurm_master[0]}}"
    #- role: 'nfs-client'
    #  NFS_MOUNTS:
    #    - fs: '{{groups.slurm_master[0]}}:/home'
    #      mountpoint: '/home'
    - slurm-client

```
That makes the setup greeen but I am not sure whether that is a valid setup, now I am getting errors from slurm:
```
root@compute001:/etc/slurm# telnet frontend001 6817
Trying 172.31.6.173...
telnet: Unable to connect to remote host: Connection timed out

```

I have tried release 1.2.0 but got into setuptools issues.

Could you please help clarifying: 

1. is NIS and NFS needed for slurm?
2. am I supposed to change only the config file or also the the playbook to make slurm work?
3. what is the current state of master more of experimental state or production capable?

Thank you

Regards,
Joe
