### ISSUE TITLE
NFS client mounts fails

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#486]
I have successfully run elasticluster setting up test-cluster over several days now. 

I have needed to add some more shared directories.  

Problem I encounter is that at the point of nfs-client role, and task "add to /etc/fstab" everything hangs, and in the end it fails with connection timeout: 

```
TASK [nfs-client : add to /etc/fstab] **************************************************************************************************************************************************************************************************
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /home: mount.nfs: Connection timed out\n"}
	to retry, use: --limit @/home/centos/elasticluster/src/elasticluster/share/playbooks/site.retry
```

Not sure where to start checking for the problem. I see that there is an earlier issue related to this when running the elasticluster start for the first time. But rerunning does not help. 

Thanks a lot in advance!
Maiken

**Comment by riccardomurri** [comment]
That task requires that (1) the NFS server is up and running, and (2)
that the clients can connect to it.  Therefore I would check that:

* The "NFS server" role/playbook has already executed before clients
  start to mount directories (the playbooks distributed with
  ElastiCluster do this, but it's not enforced in any way so you could
  get the order reversed if you write your own plays and don't know
  about this caveat).

* There's a number of protocols related to NFS, some of which run on
  unpredictable ports -- so communication between clients and server
  must be unrestricted (all ports, TCP *and* UDP).  This has been an
  issue in the past, especially on AWS.

**Comment by maikenp** [comment]
Thanks a lot for your reply. 

What I am doing is simply using the playbooks that come with elasticluster and modifying them as a first go in order to bootstrap things as much as possible. 

Where would be the most natural and correct place to define the NFS_EXPORTS snd NFS_MOUNTS so that slurm.yml and the main.yml in tasks of roles nfs-client and nfs-server knows about the variable, and not to have to define it several times?  

Or is there a nicer way to include more directories to NFS? Possibly running the after.yml playbook? What are the list of components I would have to make sure to include, and in what order? 

If this is documented somewhere, I am sorry for the question, then just point me in the right direction!

**Comment by maikenp** [comment]
Here are the changes I have made (sorry for the not optimal ansible coding)

The reason for my problems could of course be due to me doing something wrong when trying to include more directories to nfs. 

Do you see something that could be wrong? Otherwise I will contact our cloud people to see if something on their side could explain the problems. 


In groups_vars/all I have added: 
```
shared_dirs:
  - /home
  - /grid/session
  - /grid/runtime
  - /scratch/cache
```

This is my slurm.yml file:
```
- name: Slurm master Playbook
  hosts: slurm_master
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-server'
      NFS_EXPORTS:
        - path: "{{item}}"
          clients: "{{groups.slurm_worker + groups.slurm_submit|default([])}}"
      with_items: "{{ shared_dirs }}"
    - slurm-master


- name: Slurm worker nodes Playbook
  hosts: slurm_worker
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: "{{groups.slurm_master[0]}}:{{item}}"
          mountpoint: "{{item}}"
      with_items: "{{ shared_dirs }}"
    - slurm-worker


- name: Slurm submit nodes Playbook
  hosts: slurm_submit:slurm_client
  roles:
    - role: 'nis'
      NIS_MASTER: "{{groups.slurm_master[0]}}"
      when: '{{multiuser_cluster|default("true")|bool}}'
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: "{{groups.slurm_master[0]}}:{{ item}}"
          mountpoint: "{{ item }}"
      with_items: "{{ shared_dirs }}"
    - slurm-client


- name: Restart SLURMd after all config is done
  hosts: slurm_worker
  tasks:
    - service:
        name=slurmd
        state=restarted
      when: '{{is_debian_compatible}} and ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}})'
    - service:
        name=slurm-llnl
        state=restarted
      when: '{{is_debian_compatible}} and (not ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}}))'
    - service:
        name=slurmd
        state=restarted
      when: '{{is_rhel7_compatible}}'
    - service:
        name=slurm
        state=restarted
      when: '{{is_rhel6_compatible}}'
```

This is the roles/nfs-clients/defaults/main.yml file:

```
NFS_MOUNTS:
  - fs: "localhost:{{ item }}"
    mountpoint: "{{ item }}"
    with_items: "{{ shared_dirs }}"
```

The part I changed in roles/nfs-clients/tasks/main.yml is:
```
- name: Mount NFS filesystems
  tags:
    - nfs
    - nfs-client
  include: nfsmount.yml fs='{{item}}'
  with_items:
    - fs: 'localhost:/home'
      mountpoint: '/home'
    - fs: 'localhost:{{ shared_dirs[1] }}'
      mountpoint: '{{ shared_dirs[1] }}'
    - fs: 'localhost:{{ shared_dirs[2] }}'
      mountpoint: '{{ shared_dirs[2] }}'
    - fs: 'localhost:{{ shared_dirs[3] }}'
      mountpoint: '{{ shared_dirs[3] }}'
```


The roles/nfs-server/defaults/main.yml:

```
NFS_EXPORTS:
  - path: "{{ item }}"
    clients: 'localhost'
    options: 'rw,no_root_squash'
    with_items: "{{ shared_dirs }}"

arc_frontend_sessiondir: "{{ 'shared_dirs[1]' }}"
arc_frontend_runtimedir: "{{ 'shared_dirs[2]' }}"
arc_frontend_cachedir: "{{ 'shared_dirs[3]' }}"
```

In roles/nfs-server/tasks/main.yml  I have edited the blocks:

```
- name: Ensure shared dirs exist
  file:
    path: '{{ item }}'
    state: directory
  with_items: '{{ shared_dirs }}'


# exports need to be there before attempting to install/start the
# server, otherwise the service startup script might refuse to start
# the NFS server
- name: Export directories
  tags:
    - nfs
    - nfs-server
  nfsexport:
    path: '{{ item.path }}'
    clients: '{{ item.clients }}'
    options: '{{item.options|default("rw,no_root_squash,async,no_subtree_check,crossmnt")}}'
    dest: '/etc/exports'
    state: exported
  with_items:
    - path: '{{ shared_dirs[0]}}'
      clients: 'localhost'
      options: 'rw,no_root_squash'
    - path: '{{ shared_dirs[1] }}'
      clients: 'localhost'
      options: 'rw,no_root_squash'
    - path: '{{ shared_dirs[2] }}'
      clients: 'localhost'
      options: 'rw,no_root_squash'
    - path: '{{ shared_dirs[3] }}'
      clients: 'localhost'
      options: 'rw,no_root_squash'
```


In roles/nfs-client/tasks/main.yml  I have edited the last block 

```
- name: Mount NFS filesystems
  tags:
    - nfs
    - nfs-client
  include: nfsmount.yml fs='{{item}}'
  with_items:
    - fs: 'localhost:{{ shared_dirs[0] }}'
      mountpoint: '{{ shared_dirs[0] }}'
    - fs: 'localhost:{{ shared_dirs[1] }}'
      mountpoint: '{{ shared_dirs[1] }}'
    - fs: 'localhost:{{ shared_dirs[2] }}'
      mountpoint: '{{ shared_dirs[2] }}'
    - fs: 'localhost:{{ shared_dirs[3] }}'
      mountpoint: '{{ shared_dirs[3] }}'
```

**Comment by riccardomurri** [comment]
hi @maikenp

`with_items:` does not work (AFAIK) within role variable definition.
So you would need to spell out in full all the mount points you need, e.g.::

    - role: 'nfs-client'
          NFS_MOUNTS:
            - fs: "{{groups.slurm_master[0]}}:/home"
              mountpoint: "/home"
            - fs: "{{groups.slurm_master[0]}}:/grid/run"
              mountpoint: "/home"
            - fs: "{{groups.slurm_master[0]}}:/grid/run"
              mountpoint: "/home"
            # etc...

**Comment by maikenp** [comment]
I might not really understand what exactly is meant by "within role variable definition". But:

I earlier did manage to successfully add another directory to be shared, I do not have complete control of what I am now doing differently unfortunately.  However, if NFS_MOUNTS in nfs-clients/defaults/main.yml looks like: 

```NFS_MOUNTS:
  - fs: 'localhost:/home'
    mountpoint: '/home'
    options: 'rw,defaults'
  - fs: 'localhost:/grid/session'
    mountpoint: '/grid/session'
    options: 'rw,defaults'
  - fs: 'localhost:/grid/runtime'
    mountpoint: '/grid/runtime'
    options: 'rw,defaults'
  - fs: 'localhost:/scratch/cache'
    mountpoint: '/scratch/cache'
    options: 'rw,defaults'
```

Should I be able to do:
```
- name: Mount NFS filesystems
  tags:
    - nfs
    - nfs-client
  include: nfsmount.yml fs="{{item}}"
  with_items: '{{ NFS_MOUNTS }}'
```

As the playbook seems to assume I should do? 

I then get an error-message that "item" does not exist. 

And if I instead do

```
- name: Mount NFS filesystems
  tags:
    - nfs
    - nfs-client
  include: nfsmount.yml fs="{{item}}"
  with_items:
    - fs: 'localhost:/home'
      mountpoint: '/home'
      options: 'rw,defaults'
    - fs: 'localhost:/grid/session'
      mountpoint: '/grid/session'
      options: 'rw,defaults'
    - fs: 'localhost:/grid/runtime'
      mountpoint: '/grid/runtime'
      options: 'rw,defaults'
    - fs: 'localhost:/scratch/cache'
      mountpoint: '/scratch/cache'
      options: 'rw,defaults'
```

I get the same fstab problem again:

```
TASK [nfs-client : Mount NFS filesystems] **************************************************************************************************************************************************************************************************************************************************************************
included: /home/centos/elasticluster/src/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml for compute001
included: /home/centos/elasticluster/src/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml for compute001
included: /home/centos/elasticluster/src/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml for compute001
included: /home/centos/elasticluster/src/elasticluster/share/playbooks/roles/nfs-client/tasks/nfsmount.yml for compute001

TASK [nfs-client : ensure /home directory exists] ******************************************************************************************************************************************************************************************************************************************************************
ok: [compute001]

TASK [nfs-client : add to /etc/fstab] ******************************************************************************************************************************************************************************************************************************************************************************
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /home: mount.nfs: Connection timed out\n"}
	to retry, use: --limit @/home/centos/elasticluster/src/elasticluster/share/playbooks/site.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************************
compute001                 : ok=42   changed=3    unreachable=0    failed=1   
frontend001                : ok=96   changed=17   unreachable=0    failed=0   

```


Could it be on the cloud-side, and not anything to do with elasticluster?
